const LLMProvider = require('./llmProvider');

/**
 * Google Gemini LLM Provider
 * Implements Gemini-based prompt generation
 */
class GeminiLLMProvider extends LLMProvider {
  constructor(config = {}) {
    super(config);
    this.apiKey = config.apiKey || process.env.GEMINI_API_KEY;
    this.model = config.model || 'gemini-1.5-flash';
    this.baseURL = 'https://generativelanguage.googleapis.com/v1beta';
    
    if (!this.apiKey) {
      throw new Error('Gemini API key is required');
    }
  }

  /**
   * Generate marketing prompt using Gemini
   * @param {Object} businessProfile - Business profile data
   * @param {Object} template - Template data
   * @returns {Promise<string>} Generated prompt
   */
  async generatePrompt(businessProfile, template) {
    try {
      const systemPrompt = this.buildSystemPrompt(businessProfile, template);
      
      const userPrompt = `Create a compelling marketing message for a poster that:
- Highlights the unique value proposition of ${businessProfile.name}
- Includes a strong call-to-action
- Fits the ${template.style || 'professional'} style
- Is concise and impactful (max 50 words)
- Appeals to customers interested in ${businessProfile.products?.join(', ') || 'our services'}
- Incorporates the tagline: "${businessProfile.tagline}"`;

      const prompt = `${systemPrompt}\n\nTask: ${userPrompt}`;

      const response = await this.makeAPICall(`/models/${this.model}:generateContent`, {
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 200,
          stopSequences: []
        },
        safetySettings: [
          {
            category: 'HARM_CATEGORY_HARASSMENT',
            threshold: 'BLOCK_MEDIUM_AND_ABOVE'
          },
          {
            category: 'HARM_CATEGORY_HATE_SPEECH',
            threshold: 'BLOCK_MEDIUM_AND_ABOVE'
          },
          {
            category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
            threshold: 'BLOCK_MEDIUM_AND_ABOVE'
          },
          {
            category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
            threshold: 'BLOCK_MEDIUM_AND_ABOVE'
          }
        ]
      });

      if (!response.candidates || response.candidates.length === 0) {
        throw new Error('No content generated by Gemini');
      }

      const content = response.candidates[0].content;
      if (!content || !content.parts || content.parts.length === 0) {
        throw new Error('Invalid response format from Gemini');
      }

      return content.parts[0].text.trim();
    } catch (error) {
      throw new Error(`Gemini prompt generation failed: ${error.message}`);
    }
  }

  /**
   * Validate Gemini configuration
   * @returns {boolean} True if configuration is valid
   */
  validateConfig() {
    return !!(this.apiKey && this.model);
  }

  /**
   * Get Gemini LLM capabilities
   * @returns {Object} Provider capabilities
   */
  getCapabilities() {
    return {
      ...super.getCapabilities(),
      maxPromptLength: 30720, // Gemini 1.5 Flash context length
      supportedModels: ['gemini-1.5-flash', 'gemini-1.5-pro', 'gemini-1.0-pro'],
      supportedLanguages: ['en', 'es', 'fr', 'de', 'it', 'pt', 'ru', 'ja', 'ko', 'zh'],
      supportsSafetyFilters: true
    };
  }

  /**
   * Build system prompt optimized for Gemini
   * @param {Object} businessProfile - Business profile data
   * @param {Object} template - Template requirements
   * @returns {string} System prompt
   */
  buildSystemPrompt(businessProfile, template) {
    return `You are a creative marketing expert specializing in poster content creation.

BUSINESS CONTEXT:
Business: ${businessProfile.name}
Tagline: ${businessProfile.tagline}
Description: ${businessProfile.description}
Products/Services: ${businessProfile.products?.join(', ') || 'Various services'}
Brand Colors: ${businessProfile.colorPalette?.map(c => c.name).join(', ') || 'Not specified'}

TEMPLATE REQUIREMENTS:
Style: ${template.style || 'Professional'}
Target Audience: ${template.targetAudience || 'General consumers'}
Tone: ${template.tone || 'Engaging and professional'}

INSTRUCTIONS:
Create marketing copy that is:
- Emotionally engaging and memorable
- Clear and easy to understand
- Action-oriented with strong call-to-action
- Aligned with brand personality
- Optimized for visual poster format
- Culturally appropriate and inclusive

Focus on benefits over features, create urgency when appropriate, and ensure the message resonates with the target audience.`;
  }

  /**
   * Make API call to Gemini
   * @param {string} endpoint - API endpoint
   * @param {Object} data - Request data
   * @returns {Promise<Object>} API response
   */
  async makeAPICall(endpoint, data) {
    const fetch = require('node-fetch');
    
    const url = `${this.baseURL}${endpoint}?key=${this.apiKey}`;
    
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error?.message || `Gemini API request failed: ${response.status}`);
    }

    return await response.json();
  }
}

module.exports = {
  GeminiLLMProvider
};