const { GeminiLLMProvider } = require('../../../../src/services/aiProviders/geminiProvider');

// Mock node-fetch
const mockFetch = jest.fn();
jest.mock('node-fetch', () => mockFetch);

describe('GeminiLLMProvider', () => {
  let provider;
  const mockConfig = {
    apiKey: 'test-api-key',
    model: 'gemini-1.5-flash'
  };

  beforeEach(() => {
    provider = new GeminiLLMProvider(mockConfig);
    mockFetch.mockClear();
  });

  describe('Constructor', () => {
    it('should initialize with provided config', () => {
      expect(provider.apiKey).toBe('test-api-key');
      expect(provider.model).toBe('gemini-1.5-flash');
      expect(provider.baseURL).toBe('https://generativelanguage.googleapis.com/v1beta');
    });

    it('should use environment variables as fallback', () => {
      process.env.GEMINI_API_KEY = 'env-api-key';
      const envProvider = new GeminiLLMProvider();
      expect(envProvider.apiKey).toBe('env-api-key');
      expect(envProvider.model).toBe('gemini-1.5-flash');
      delete process.env.GEMINI_API_KEY;
    });

    it('should throw error if no API key provided', () => {
      expect(() => new GeminiLLMProvider({})).toThrow('Gemini API key is required');
    });
  });

  describe('generatePrompt', () => {
    const businessProfile = {
      name: 'Acme Corp',
      tagline: 'Quality Products',
      description: 'We make great stuff',
      products: ['Widget A', 'Widget B']
    };
    const template = { style: 'professional' };

    it('should generate prompt successfully', async () => {
      const mockResponse = {
        candidates: [{
          content: {
            parts: [{
              text: 'Generated marketing prompt for Acme Corp'
            }]
          }
        }]
      };

      mockFetch.mockResolvedValue({
        ok: true,
        json: () => Promise.resolve(mockResponse)
      });

      const result = await provider.generatePrompt(businessProfile, template);
      expect(result).toBe('Generated marketing prompt for Acme Corp');
    });

    it('should handle API errors', async () => {
      mockFetch.mockResolvedValue({
        ok: false,
        json: () => Promise.resolve({
          error: { message: 'API quota exceeded' }
        })
      });

      await expect(provider.generatePrompt(businessProfile, template))
        .rejects.toThrow('Gemini prompt generation failed: API quota exceeded');
    });

    it('should handle empty response', async () => {
      const mockResponse = { candidates: [] };

      mockFetch.mockResolvedValue({
        ok: true,
        json: () => Promise.resolve(mockResponse)
      });

      await expect(provider.generatePrompt(businessProfile, template))
        .rejects.toThrow('Gemini prompt generation failed: No content generated by Gemini');
    });

    it('should handle invalid response format', async () => {
      const mockResponse = {
        candidates: [{
          content: { parts: [] }
        }]
      };

      mockFetch.mockResolvedValue({
        ok: true,
        json: () => Promise.resolve(mockResponse)
      });

      await expect(provider.generatePrompt(businessProfile, template))
        .rejects.toThrow('Gemini prompt generation failed: Invalid response format from Gemini');
    });
  });

  describe('validateConfig', () => {
    it('should return true for valid config', () => {
      expect(provider.validateConfig()).toBe(true);
    });

    it('should return false for missing API key', () => {
      provider.apiKey = null;
      expect(provider.validateConfig()).toBe(false);
    });
  });

  describe('getCapabilities', () => {
    it('should return Gemini LLM capabilities', () => {
      const capabilities = provider.getCapabilities();

      expect(capabilities.maxPromptLength).toBe(30720);
      expect(capabilities.supportedModels).toContain('gemini-1.5-flash');
      expect(capabilities.supportedLanguages).toContain('en');
      expect(capabilities.supportsSafetyFilters).toBe(true);
    });
  });
});